import { extendTheme, theme } from "@chakra-ui/react";

const defaultTheme = {
    colors: {
        calendar: {
            bg: "#fff",
            text: "#333",
            headerBg: "#f7f7f7",
            button: "#333",
            buttonHover: "#007bff",
            selectBg: "#fff",
            selectColor: "#333",
            selectBorder: "#ccc",
            info: "#007bff",
            dayLabelBg: "#fafafa",
            dayLabel: "#555",
            border: "#e1e1e1",
            emptyCellBg: "#fafafa",
            summary: "#777",
            summaryBg: "#f7f7f7",
            cellBg: "#fff",
            cellHoverBg: "#f0f8ff",
            cellHoverBorder: "#b3d7ff",
            todayBg: "#007bff",
            todayColor: "#fff",
            inRangeBg: "rgba(0, 191, 255, 0.1)",
            rangeEndBg: "rgba(0, 191, 255, 0.3)",
            rangeShadow: "#00bfff",
            tooltipBg: "#333",
            tooltipColor: "#fff",
            volumeBar: "#4fc3f7",
            volumeBarAlt: "#fff",
            volBarBg: "rgba(0, 0, 0, 0.2)",
            overlayBg: "rgba(0, 0, 0, 0.5)",
            drawerBg: "#fff",
            closeBtn: "#333",
            zoomBtnBg: "#007bff",
            zoomBtnColor: "#fff",
            zoomBtnHover: "#005bb5",
            badgeBg: "#007bff",
            badgeColor: "#fff",
            alertBg: "#ff4560",
            alertColor: "#fff",
            anomalyBorder: "#ff4560",
        },
    },
};

const highContrastTheme = {
    colors: {
        calendar: {
            bg: "#000",
            text: "#fff",
            headerBg: "#333",
            button: "#fff",
            buttonHover: "#00f",
            selectBg: "#000",
            selectColor: "#fff",
            selectBorder: "#fff",
            info: "#00f",
            dayLabelBg: "#333",
            dayLabel: "#fff",
            border: "#fff",
            emptyCellBg: "#333",
            summary: "#ccc",
            summaryBg: "#333",
            cellBg: "#000",
            cellHoverBg: "#444",
            cellHoverBorder: "#00f",
            todayBg: "#00f",
            todayColor: "#fff",
            inRangeBg: "rgba(0, 0, 255, 0.2)",
            rangeEndBg: "rgba(0, 0, 255, 0.4)",
            rangeShadow: "#00f",
            tooltipBg: "#fff",
            tooltipColor: "#000",
            volumeBar: "#00f",
            volumeBarAlt: "#000",
            volBarBg: "rgba(255, 255, 255, 0.2)",
            overlayBg: "rgba(0, 0, 0, 0.8)",
            drawerBg: "#000",
            closeBtn: "#fff",
            zoomBtnBg: "#00f",
            zoomBtnColor: "#fff",
            zoomBtnHover: "#005bb5",
            badgeBg: "#00f",
            badgeColor: "#fff",
            alertBg: "#f00",
            alertColor: "#fff",
            anomalyBorder: "#f00",
        },
    },
};

const colorblindTheme = {
    colors: {
        calendar: {
            bg: "#fff",
            text: "#000",
            headerBg: "#e0e0e0",
            button: "#000",
            buttonHover: "#005566",
            selectBg: "#fff",
            selectColor: "#000",
            selectBorder: "#666",
            info: "#005566",
            dayLabelBg: "#e0e0e0",
            dayLabel: "#000",
            border: "#666",
            emptyCellBg: "#e0e0e0",
            summary: "#555",
            summaryBg: "#e0e0e0",
            cellBg: "#fff",
            cellHoverBg: "#d0e0e0",
            cellHoverBorder: "#005566",
            todayBg: "#005566",
            todayColor: "#fff",
            inRangeBg: "rgba(0, 85, 102, 0.1)",
            rangeEndBg: "rgba(0, 85, 102, 0.3)",
            rangeShadow: "#005566",
            tooltipBg: "#000",
            tooltipColor: "#fff",
            volumeBar: "#005566",
            volumeBarAlt: "#fff",
            volBarBg: "rgba(0, 0, 0, 0.2)",
            overlayBg: "rgba(0, 0, 0, 0.5)",
            drawerBg: "#fff",
            closeBtn: "#000",
            zoomBtnBg: "#005566",
            zoomBtnColor: "#fff",
            zoomBtnHover: "#003d4d",
            badgeBg: "#005566",
            badgeColor: "#fff",
            alertBg: "#b22222",
            alertColor: "#fff",
            anomalyBorder: "#b22222",
        },
    },
};

export const themes = {
    default: extendTheme(defaultTheme),
    highContrast: extendTheme(highContrastTheme),
    colorblind: extendTheme(colorblindTheme),
};

export default theme;